### ISSUE TITLE
Error can't find include file "rabbit_framing.hrl" when build with rebar3

### ISSUE THREAD

**Issue by nguyenbatam** [rabbitmq/rabbitmq-common#103]
When i build rabbitmq-common with rebar3  . I have this error . Some one help me
rebar3  compile
===> Verifying dependencies...
===> Package <<"rebar_gdb_plugin">> not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /home/tamnb/.cache/rebar3/hex/default/registry
===> Generating package index...
===> [cloudi_service_oauth1:1.5.1] Only existing version of cloudi_service_db_riak is 1.3.3 which does not match constraint ~> 1.5.1. Using anyway, but it is not guaranteed to work.
===> Writing index to /home/tamnb/.cache/rebar3/hex/default/packages.idx
===> Plugin rebar_gdb_plugin not available. It will not be used.
===> Compiling rabbit_common
===> Compiling /home/tamnb/workspace_Erlang/my_project/_build/default/lib/rabbit_common/src/rabbit_misc.erl failed
/home/tamnb/workspace_Erlang/my_project/_build/default/lib/rabbit_common/src/rabbit_misc.erl:19: can't find include file "rabbit_framing.hrl"

This is my config
{erl_opts, [debug_info,{parse_transform, lager_transform}]}.
{deps, [{lager,"3.0.2",
		{git,"https://github.com/basho/lager.git",{tag,"3.0.2"}}},
	{protobuffs,"0.8.2",
		{git,"https://github.com/basho/erlang_protobuffs.git",{tag,"0.8.2"}}},
	{eredis,"1.0.8",
		{git,"https://github.com/wooga/eredis.git",{tag,"v1.0.8"}}},
	{jiffy,"0.14.7",
		{git,"https://github.com/davisp/jiffy.git",{tag,"0.14.7"}}},
  {cowboy, "1.0.4",
		{git, "https://github.com/ninenines/cowboy.git",{tag,"1.0.4"}}},
  {rabbit_common, ".*",
    {git, "git://github.com/jbrisbin/rabbit_common.git", "rabbitmq-3.5.6"}},
  {amqp_client,".*",
    {git,"https://github.com/rabbitmq/rabbitmq-erlang-client.git",{tag,"rabbitmq_v3_5_3"}}}
]}.

{relx, [{release, { my_project, "0.1.0" },
         [my_project,
          sasl]},

        {sys_config, "./config/sys.config"},
        {vm_args, "./config/vm.args"},

        {dev_mode, true},
        {include_erts, false},

        {extended_start_script, true}]
}.

{profiles, [{prod, [{relx, [{dev_mode, false},
                            {include_erts, true}]}]
            }]
}.

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

Protocol framing files are generated by [rabbitmq-codegen](https://github.com/rabbitmq/rabbitmq-codegen).
