### ISSUE TITLE
Add an option to suppress test console output

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-common#109]
`make tests` with common test are producing a lot of garbage console output. There will be `html` logs generated and most of this output is useless. This output can be sent to log file and console can be filled with dots or some nicer messages, which will still keep `travis` happy, but won't frustrate developers.

**Comment by binarin** [comment]
Have you tried https://github.com/ferd/cth_readable ? E.g. `cth_readable_failonly`, which only outputs error and SASL logs to the shell in case of failures.

**Comment by michaelklishin** [comment]
Looks like https://github.com/ferd/cth_readable is what we want.

**Comment by binarin** [comment]
`cth_readable` dependency can be used after either https://github.com/project-fifo/cf/pull/2 or https://github.com/ninenines/erlang.mk/issues/586 is solved.

**Comment by essen** [comment]
I think RabbitMQ already suppresses output. In any case the Erlang.mk ticket referenced has been fixed today and should be available soon-ish in RabbitMQ.

**Comment by hairyhum** [comment]
https://github.com/rabbitmq/cth_styledout is addressing this issue for rabbitmq to some extent.
