### ISSUE TITLE
rabbit_misc.erl:19: can't find include file "rabbit_framing.hrl

### ISSUE THREAD

**Issue by qingchuwudi** [rabbitmq/rabbitmq-common#127]
I'm using `rebar` to compile, and add `https://github.com/rabbitmq/rabbitmq-common.git` to deps.

But:
```bash
/xx/deps/rabbit_common/src/rabbit_misc.erl:19: can't find include file "rabbit_framing.hrl"
Compiling /xx/deps/rabbit_common/src/rabbit_misc.erl failed:
ERROR: compile failed while processing /xx/deps/rabbit_common: rebar_abort
Makefile:13: recipe for target 'compile' failed
make: *** [compile] Error 1
```
While everything is ok , if make in `deps/rabbitmq_common/`. 

Any pointers or suggestions would be greatly appreciated.

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
Protocol framing modules and header files are generated by `rabbitmq_codegen`.

**Comment by michaelklishin** [comment]
Yeah, and RabbitMQ doesn't use rebar, so unless you build `rabbitmq_common` with `make` as a separate step, it isn't really Rebar-compatible.

**Comment by qingchuwudi** [comment]
Thanks. And  I have made it done.
