### ISSUE TITLE
Add the Options parameter to rabbit_json 

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-common#164]
The current implementation exposes only:

```
decode(JSON) ->
    jsx:decode(JSON, [return_maps]).
```

The JSX library supports different parameters for [`decode`](https://github.com/talentdeficit/jsx#decode12) and [ `encode`](https://github.com/talentdeficit/jsx#encode12) functions

It is useful to expose all these interfaces for future implementations and also for plugins that use the `rabbit_json`.

I am working on this [issue](https://github.com/aweber/rabbitmq-autocluster/issues/120) on  rabbitmq-autocluster, and I had to add use `jsx:decode` directly. See this [comment](https://github.com/aweber/rabbitmq-autocluster/issues/120#issuecomment-274853144) .

This is what I have in mind to do:
```
-spec decode(jsx:json_text()) -> jsx:json_term().
decode(JSON) ->
    decode(JSON, []).


-spec decode(jsx:json_text(), jsx_to_term:config()) -> jsx:json_term().
decode(JSON, Opts) ->
    jsx:decode(JSON, Opts).
```

**There is a little side effect:**

Currently, the other RabbitMQ modules use this interface:
```
rabbit_json:try_decode(Defn) %% this interface implicitly uses  `[return_maps]`
```

and it should be replaced with:
```
rabbit_json:try_decode(Defn, [return_maps]) 
```

I already tried to modify the interface by adding `[return_maps]`, then ran the unit tests on the management ui and they passed

**Comment by michaelklishin** [comment]
@Gsantomaggio there's still time to update all callers for `3.7.0` :)
