### ISSUE TITLE
Channels aren't cleaned properly when connections are brutally killed

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-common#167]
When rabbitmq-perf-test producers crashed with out-of-memory errors, 97 channels were left behind:

```
Error on AMQP connection <0.3361.0> (10.0.16.31:50086 -> 10.0.16.23:5672, vhost: '8961921b-36f6-48e0-9553-0351c7783376', user: '600878f0-8001-41e3-8198-986d941db2eb', state: running), channel 5:error while terminating:
killed
```

There were 97 instances of the above error in the rabbit log.

**Comment by michaelklishin** [comment]
The issue ended up being the following: when a connection has to shut down and tells its channels to stop, if a channel took longer than a `timeout` to do so, it was brutally killed (as in Erlang supervisors) and its stats table records were not cleaned up.
