### ISSUE TITLE
If test dependency fails to build, CT fails with undef.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-common#192]
Sometimes when test dependencies for plugins (`rabbitmq_ct_helpers` or `rabbitmq_ct_client_helpers`) fail to build, the test suite still starts and could fail with `undef` error.
It's not very clear from the test results what was wrong. And the build error can be lost `make test` output.
It probably makes sense to stop `make test` when test dependency could not be built.

**Comment by dumbbell** [comment]
I noticed that several times too. The problem comes from Erlang.mk; I'll submit a patch.

**Comment by dumbbell** [comment]
See ninenines/erlang.mk#698.

**Comment by dumbbell** [comment]
Our patch was merged into Erlang.mk and `erlang.mk` was updated in all our projects, both `stable` and `master`. Thus this should be fixed.
