### ISSUE TITLE
gen_server2 stats do not allow the process to hibernate

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-common#196]
The implementation of the new `gen_server2` stats (RabbitMQ >= 3.6.7) wakes up the process before it has the chance to go into hibernation (mailbox messages). The stats timer should be stopped when `pre_hibernate` is being handled, and restarted in `post_hibernate`.

**Comment by glyn** [comment]
@dcorbacho Thanks for raising this. Please could you confirm that `gen_server2` first appeared in RabbitMQ 3.6.8 (you wrote "RabbitMQ > 3.6.7" above)?

Also, I would like to note the symptoms we saw as this may help other end users to know whether this bug affects them. A RabbitMQ queue reported "idle time" values no older than about one minute in spite of no messages being written to or read from the queue for well over 2 minutes. It seemed that something was happening every minute or that counted as activity on the queue.

**Comment by dcorbacho** [comment]
@glyn Sorry, it should have been >= 3.6.7 (amended). `gen_server2` is an old extension of `gen_server` in RabbitMQ, but in [3.6.7](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_7) we introduced an enhancement to notify the internal buffer length and publish it on [`rabbitmq-top`](https://github.com/rabbitmq/rabbitmq-top/issues/20)

**Comment by glyn** [comment]
Thanks for the correction @dcorbacho.
