### ISSUE TITLE
Integrate Looking Glass

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-common#198]
When we run `make run-broker` we want to conditionally enable the Looking Glass tracer with trace pattern of our choosing. For example, `make run-broker RABBITMQ_TRACER=rabbit_tracer:connections` would trace all the connection processes. Then once tracing is done, `make profile` will build callgrind.out files that can then be opened with qcachegrind.

**Comment by michaelklishin** [comment]
Using environment variables to trace one or more modules (or functions) would be great. Would 
a comma-separated list be sufficient here?

**Comment by essen** [comment]
You provide a comma separated list of M:F which contain specifications for what you want to trace. More info in the coming PRs.

**Comment by essen** [comment]
We also need to make Looking Glass "proper" with a LICENSE, README and whatnot. Same for the lz4-erlang dependency. Is there any guideline as to what I should add?

**Comment by michaelklishin** [comment]
@essen I can help with those.
