### ISSUE TITLE
`delegate:cast/2` can cause binary heap growth in some scenarios

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-common#208]
Under some conditions, the memory usage of binaries by mirror queues / `gm` processes causes the system to crash. This has been nailed down to the case when `ack`/`nack` are sent to the node hosting the queue `slave`. In that case, the only difference between sending `ack`/`nack` to `master` or `slave` is the call to `delegate:cast`, which will either send directly to the local process (publishing to `master`), or send to the remote delegate (publishing to `slave`). 

A simple code refactor seems to deeply alleviate this problem, which I assume changes the handling of the binary references by the Erlang VM.

**Comment by dcorbacho** [comment]
Memory growth issue:
<img width="1252" alt="memory_leak" src="https://user-images.githubusercontent.com/646577/27581270-249e09e8-5b25-11e7-87f8-b707d507705f.png">

With https://github.com/rabbitmq/rabbitmq-common/pull/210 patch applied to simplify function calls:
<img width="1187" alt="delegate_patch" src="https://user-images.githubusercontent.com/646577/27581269-248d376c-5b25-11e7-8e0d-e621035a9a98.png">

**Comment by davidpdw** [comment]
@dcorbacho Hello, what will lead to this bug, what will happen? Could you describe it in detail, thank you very much. Because when I use rabbitmq in 3.6.10, sometimes producer connection flow,it looks like system crashed, I want to determine if it is caused by this problem.
