### ISSUE TITLE
rabbitmq treating 's' in table items as short int though specification say 'U' is for short int, and 's' for short string

### ISSUE THREAD

**Issue by allan-simon** [rabbitmq/rabbitmq-common#261]
https://github.com/rabbitmq/rabbitmq-common/blob/2b54e78098b6e8cd994cc2475dd273a70e47da1f/src/rabbit_binary_parser.erl#L118

but we in the specification 
https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf

section 4.2.1 we have 

```
field-value         = 't' boolean

                    / 'U' short-int
                    / 'u' short-uint

                    / 's' short-string    
```

**Comment by michaelklishin** [comment]
See [Errata](http://www.rabbitmq.com/amqp-0-9-1-errata.html). This has been the case for a decade since AMQP 0-9-1 is effectively frozen in time.

**Comment by allan-simon** [comment]
thanks for the pointer
