### ISSUE TITLE
Missing "sslsocket" causing build failure

### ISSUE THREAD

**Issue by palfrey** [rabbitmq/rabbitmq-common#27]
Previously (as in within the last 2 weeks) I was able to have rabbitmq-common as a dependency of my plugin project and the build worked. Now, it doesn't appear to work, and certainly when checking out current master on it's own I get build failures. Entirely possible this is a bug in my local system, or that I'm missing a dependency, but I can't see anything obvious. Might be related to #8 given where the issues are occurring, but that's a complete guess.

Any thoughts?

```
root@ae0389c87456:/rabbit/rabbitmq-common# make
 DEP    rabbitmq_codegen
 GEN    include/rabbit_framing.hrl
 GEN    src/rabbit_framing_amqp_0_8.erl
 GEN    src/rabbit_framing_amqp_0_9_1.erl
 DEPEND rabbit_common.d
 ERLC   app_utils.erl credit_flow.erl gen_server2.erl mirrored_supervisor.erl mochijson2.erl pmon.erl priority_queue.erl rabbit_amqqueue.erl rabbit_auth_mechanism.erl rabbit_authn_backend.erl rabbit_authz_backend.erl rabbit_backing_queue.erl rabbit_basic.erl rabbit_binary_generator.erl rabbit_binary_parser.erl rabbit_channel.erl rabbit_channel_interceptor.erl rabbit_command_assembler.erl rabbit_control_misc.erl rabbit_event.erl rabbit_exchange_decorator.erl rabbit_exchange_type.erl rabbit_framing_amqp_0_8.erl rabbit_framing_amqp_0_9_1.erl rabbit_heartbeat.erl rabbit_misc.erl rabbit_msg_store_index.erl rabbit_net.erl rabbit_networking.erl rabbit_nodes.erl rabbit_password_hashing.erl rabbit_policy_validator.erl rabbit_queue_collector.erl rabbit_queue_decorator.erl rabbit_queue_master_locator.erl rabbit_reader.erl rabbit_runtime_parameter.erl rabbit_writer.erl ssl_compat.erl supervisor2.erl time_compat.erl
src/rabbit_net.erl:27: can't find include lib "ssl/src/ssl_api.hrl"
src/rabbit_net.erl:99: record sslsocket undefined
src/rabbit_net.erl:109: record sslsocket undefined
src/rabbit_net.erl:114: record sslsocket undefined
src/rabbit_net.erl:119: record sslsocket undefined
src/rabbit_net.erl:124: record sslsocket undefined
src/rabbit_net.erl:137: record sslsocket undefined
src/rabbit_net.erl:142: record sslsocket undefined
src/rabbit_net.erl:156: record sslsocket undefined
src/rabbit_net.erl:165: record sslsocket undefined
src/rabbit_net.erl:170: record sslsocket undefined
src/rabbit_net.erl:175: record sslsocket undefined
src/rabbit_net.erl:178: record sslsocket undefined
src/rabbit_net.erl:181: record sslsocket undefined
src/rabbit_net.erl:207: record sslsocket undefined
src/rabbit_net.erl:210: record sslsocket undefined
src/rabbit_net.erl:213: record sslsocket undefined
src/rabbit_net.erl:251: record sslsocket undefined
erlang.mk:4919: recipe for target 'ebin/rabbit_common.app' failed
make[1]: *** [ebin/rabbit_common.app] Error 1
erlang.mk:4756: recipe for target 'app' failed
make: *** [app] Error 2
```

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list.

@essen and @dumbbell obviously understand `erlang.mk` better than I do but have you tried rebuilding your plugin from scratch? What OTP version do you use?

**Comment by essen** [comment]
It's related to the Ranch merge, the sslsocket record doesn't exist anymore. I'm not sure why you get this error though, if you look here the sslsocket record is gone: https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_net.erl

**Comment by palfrey** [comment]
So, FYI, I've managed to fix this. This was a Ubuntu 15.10 image (building under Docker) so OTP 18, and it turns out the missing package was `erlang-src`. Note that rabbitmq-common could be built without this recently (probably prior to the ranch merge)

**Comment by essen** [comment]
I now realize my previous comment was completely out of the loop. Sorry.

Doubt Ranch would do this, on the other hand maybe the Erlang.mk switch did it, since this changed most of the build configuration.

**Comment by htk** [comment]
I built on debian wheezy:
src/rabbit_net.erl:27: can't find include lib "ssl/src/ssl_api.hrl"
@palfrey

**Comment by michaelklishin** [comment]
Erlang's `ssl` app is now a **compile time** dependency. Make sure you have the necessary packages installed on Debian and Ubuntu if you want to build from source.

**Comment by dumbbell** [comment]
Because this header is in a `src` directory instead of `include`, it's not available in the `erlang-dev` package, but in the `erlang-src` package. I'm going to update the build prerequisite on the website.

**Comment by michaelklishin** [comment]
For those experiencing this issue, you need to install `erlang-src` as well as other Erlang packages, e.g.

```
sudo apt-get install -y erlang-nox erlang-dev erlang-src
```

**Comment by KoFish** [comment]
Solved this by copying `ssl_api.hrl` and `ssl_chipher.hrl` from a copy of the erlang-otp source into `rabbit_common/include/ssl/src/` and that seems really rather broken if you ask me. Especially since the only thing that is needed to make this work is one record definition that has two fields `-record(sslsocket, {fd = nil, pid = nil}).`. But instead I should be required to install the equivalent of erlang-src package on whatever distribution of linux I'm on?

**Comment by michaelklishin** [comment]
@KoFish the right thing to do is to make sure your Erlang/OTP installation has the headers.

**Comment by KoFish** [comment]
@michaelklishin which on a debian machine requires erlang-src to be installed? Or am I missing something?

**Comment by michaelklishin** [comment]
@KoFish see above.

**Comment by AndrewDryga** [comment]
A few years later.. This one is still very weird because everybody who is including `rabbit_common` as a dependency (pretty much everybody who use RabbitMQ in Elixir or Erlang) need to add headers just because of that one file. And those headers are stripped in a lot of Erlang/Elixir Linux Alpine containers to reduce size.

**Comment by essen** [comment]
Can you post the errors you get? A quick look at the rabbit_net file suggests it might not be necessary to include this header anymore?

**Comment by AndrewDryga** [comment]
Thank you anyways. I heard that 3.7.9 (or something) should address issues that stop us from bumping the versions.

**Comment by essen** [comment]
I've opened https://github.com/rabbitmq/rabbitmq-common/pull/276

I'd appreciate if you could test it, even if it's not going to be immediately useful to you.
