### ISSUE TITLE
rabbitmq_codegen should be a build dep

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-common#28]
Here: https://github.com/rabbitmq/rabbitmq-common/blob/master/Makefile#L3

Putting it in DEPS means Erlang.mk will consider it to be an Erlang application and add it to the 'applications' key in the .app file if autopatch is used (the normal scenario when Erlang.mk users add it as DEPS). It should be a BUILD_DEPS.

@dumbbell ping

**Comment by dumbbell** [comment]
Fixed in e0eb817b0459a6e60b6ca416ff64cb895d3447b0.
