### ISSUE TITLE
Duplicated modules

### ISSUE THREAD

**Issue by DennisKh** [rabbitmq/rabbitmq-common#304]
Please help solve this problem. It appears when I try to create a new tag on Gitlab, but everything works locally
```
Release failed, during .boot generation:
        Duplicated modules: 
    	mochiweb_util specified in rabbit_common and mochiweb
    	mochinum specified in rabbit_common and mochiweb
    	mochijson2 specified in rabbit_common and mochiweb
The command '/bin/sh -c mix release --env=prod --no-tar' returned a non-zero code: 1
```
My deps:
```
[
      {:phoenix, "~> 1.3.4"}, 
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.4"},
      {:mariaex, "~> 0.8.4"},
      {:phoenix_html, "~> 2.13.0"}, #2.12.0
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:plug_cowboy, "~> 1.0"},
      {:drab, "~> 0.10.1"}, #0.10.0
      {:ecto, "~> 2.2.1"},
      {:tzdata, "0.5.19"},
      {:timex, "3.4.2"},
      {:distillery, "~> 2.0", runtime: false},
      {:exoml, "0.0.2"},
      {:httpoison, "~> 1.3.0"},
      {:browser, "~> 0.4.3"},
      {:amqp, "~> 0.2.2"}
    ]
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Modern RabbitMQ versions do not use or depend on Mochiweb or mochijson2:

 * [rabbitmq-common modules](https://github.com/rabbitmq/rabbitmq-common/tree/v3.7.x/src)
 * [rabbitmq-common code search](https://github.com/rabbitmq/rabbitmq-common/search?q=mochijson&unscoped_q=mochijson)
 * [rabbitmq-server code search](https://github.com/rabbitmq/rabbitmq-server/search?q=mochijson&unscoped_q=mochijson)

So your RabbitMQ client dependency probably needs updating.

**Comment by DennisKh** [comment]
Thank you for your help!
- Server: **nginx**
- Code used as in the documentation
```
case Connection.open url do
        {:ok, connection} ->
          case Channel.open(connection) do

            {:ok, channel} ->
                Queue.declare(channel, conf[:queue], durable: true)
                Exchange.declare(channel, conf[:exchanges], :topic)
                Queue.bind(channel, conf[:queue], conf[:exchanges], routing_key: conf[:routing_key])

                try do
                  case Basic.publish(channel, conf[:exchanges], conf[:queue], "#{message}", persistent: true) do
                    :ok ->
                      Connection.close(connection)
                      %{"status"=>1}
                    _ ->
                      Connection.close(connection)
                  end
                rescue
                  e ->
                    Connection.close(connection)
                    message_letter = "Push Message #{e.message} in function #{e.function}, arity #{e.arity} in module #{e.module}"
                    send_message_error(message_letter)
                end
            _ ->
              Connection.close(connection)
              message_letter = "Channel of Connection of PaymentsRabbitMq  not created"
              send_message_error(message_letter)

          end

        _ ->
        message_letter = "Connection of PaymentsRabbitMq  not created"
        send_message_error(message_letter)
      end
```
- Full exception stack traces:

```
Generated ex_credit app
==> Assembling release..
==> Building release ex_credit:0.0.1 using environment prod
==> Including ERTS 10.0.5 from /usr/local/lib/erlang/erts-10.0.5
==> Release failed, during .boot generation:
        Duplicated modules: 
    	mochiweb_util specified in rabbit_common and mochiweb
    	mochinum specified in rabbit_common and mochiweb
    	mochijson2 specified in rabbit_common and mochiweb
The command '/bin/sh -c mix release --env=prod --no-tar' returned a non-zero code: 1
ERROR: Job failed: command terminated with exit code 1

```

**Comment by lukebakken** [comment]
@DennisKh - please carefully read @michaelklishin 's [comment](https://github.com/rabbitmq/rabbitmq-common/issues/304#issuecomment-464343928).

Since `rabbit_common` hasn't required `mochi*` modules in a long time, there **must** be something wrong with your build environment. If you require further assistance, please provide a project that can reproduce this and post a message to the [`rabbitmq-users` mailing list](https://groups.google.com/forum/?pli=1#!forum/rabbitmq-users).
