### ISSUE TITLE
Use new logger

### ISSUE THREAD

**Issue by fenollp** [rabbitmq/rabbitmq-common#312]
This project depends on `lager` right now. It'd be nice if it'd use the built in OTP logger instead, available since OTP22.

**Comment by michaelklishin** [comment]
It would be pretty nice but there are many practical issues with that for us. We cannot require OTP 21.3 before 3.8.0. Even then, the new OTP logger does not support several Lager features and it's not extensible to the same degree. For example, we support logging to Syslog easily with Lager.

The new logger is also anything but mature. So perhaps one day it would be suitable as a Lager replacement for RabbitMQ but not today.
