### ISSUE TITLE
Codegen scripts don't work with Python 3

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-common#36]
Many systems today come with Python 3 being the default "python". But the codegen scripts don't work with it. We should support both Python 2 and 3.

Patch incoming.

**Comment by essen** [comment]
Ready to be reviewed.

**Comment by dumbbell** [comment]
I tested the two pull requests and it's working for me too. I compared the files generated with Python 3 to the files generated with Python 2 without these branches, and there is no difference (beside an unordered list with a different order).

There are two more places needing a similar patch:
* rabbitmq-amqp1.0
* rabbitmq-java-client

I will work on them.

**Comment by essen** [comment]
:birthday:
