### ISSUE TITLE
Make files seem to be incompatible with make 4.3

### ISSUE THREAD

**Issue by adeptg** [rabbitmq/rabbitmq-common#405]
I'm trying to build ranbitmq-server in Debian Sid, and it fails with this error:

```
make[3]: Leaving directory '/root/rabbitmq-server_new_hope/deps/rabbitmq_peer_discovery_etcd'
 GEN    dist
make[3]: Entering directory '/root/rabbitmq-server_new_hope'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
/root/rabbitmq-server_new_hope/deps/rabbit_common/mk/rabbitmq-dist.mk:152: *** target pattern contains no '%'.  Stop.
make[3]: Leaving directory '/root/rabbitmq-server_new_hope'
make[2]: *** [/root/rabbitmq-server_new_hope/deps/rabbit_common/mk/rabbitmq-dist.mk:217: dist] Error 2
make[2]: Leaving directory '/root/rabbitmq-server_new_hope'
dh_auto_install: error: make -j8 install DESTDIR=/root/rabbitmq-server_new_hope/debian/rabbitmq-server AM_UPDATE_INFO_DIR=no returned exit code 2
make[1]: *** [debian/rules:29: override_dh_auto_install] Error 2
make[1]: Leaving directory '/root/rabbitmq-server_new_hope'
make: *** [debian/rules:11: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

I'm using this archive: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.5/rabbitmq-server-3.8.5.tar.xz
I can build the same version in Debian Testing without any issue.
The root cause could be the new version of GNU make: 4.3 in unstable vs 4.2 in testing.
Also, here is the  Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964636

**Comment by michaelklishin** [comment]
Here is the [line in question](https://github.com/rabbitmq/rabbitmq-common/blob/master/mk/rabbitmq-dist.mk#L152). I am trying to reproduce. Some [discussed reasons](https://stackoverflow.com/questions/15113138/target-pattern-contains-no-makefile) seem to vary.

**Comment by michaelklishin** [comment]
I cannot reproduce using a Sid container started like this:

``` shell
docker run -i -t debian:sid /bin/bash
```

the server and all dependencies build successfully and I can confirm that the Make version installed is `4.3`. @adeptg what exactly is the Make target used in your case?

**Comment by michaelklishin** [comment]
```
make dist
```

also works for me on Sid.

I only could reproduce it late in the run of

```
make package-deb
```

from an [umbrella clone](https://github.com/rabbitmq/rabbitmq-public-umbrella/).

**Comment by michaelklishin** [comment]
I have tried escaping of the `%` and it seems to be a red herring. The real issue is something else. I am out of my Makefile depth here, unfortunately.

**Comment by lukebakken** [comment]
For what it's worth both `make dist` and `make package-generic-unix` work fine via the umbrella on my workstation. Arch Linux, GNU make version 4.3

**Comment by adeptg** [comment]
Thanks for checking! If it's not the new make version, it's something else (probably, something in debian/rules).
I'm trying to build it this way:
git clone https://salsa.debian.org/openstack-team/third-party/rabbitmq-server.git
dpkg-buildpackage -uc -us

Will look further into it

**Comment by lukebakken** [comment]
I suggest starting with the openstack team.

**Comment by michaelklishin** [comment]
@adeptg that's the Debian package I believe (from the core Debian and Ubuntu repositories). Our team has maintained [our own](https://github.com/rabbitmq/rabbitmq-server-release/tree/master/packaging/debs/Debian) for many years.

**Comment by michaelklishin** [comment]
@lukebakken note that I could reproduce the failure on Sid so perhaps it can be reopened?

**Comment by lukebakken** [comment]
@michaelklishin when you ran `debian:sid` from docker I'm assuming you had to install a bunch of packages to get the build to work, correct?

**Comment by lukebakken** [comment]
Yep, reproduced via `debian:sid` container -

```
make[6]: Entering directory '/root/rabbitmq-public-umbrella/deps/rabbitmq_server_release/packaging/debs/Debian/rabbitmq-server-3.8.0+rc.1.46.g92e0902'
make[6]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
/root/rabbitmq-public-umbrella/deps/rabbitmq_server_release/packaging/debs/Debian/rabbitmq-server-3.8.0+rc.1.46.g92e0902/deps/rabbit_common/mk/rabbitmq-dist.mk:152: *** target pattern contains no '%'.  Stop.
make[6]: Leaving directory '/root/rabbitmq-public-umbrella/deps/rabbitmq_server_release/packaging/debs/Debian/rabbitmq-server-3.8.0+rc.1.46.g92e0902'
```

**Comment by lukebakken** [comment]
This seems like something for @dumbbell or @essen to check out since they have GNU make skills.

**Comment by dumbbell** [comment]
Hi!

I started to look at this problem. I can reproduce with Debian Sid and the official Debian package of RabbitMQ (3.8.3).

`make dist` invoked by `make install` during the build of the Debian package fails with the error reported in this issue. However `make dist` invoked by `make dist` earlier during the build works correctly. I can't reproduce outside of the build of the Debian package and I'm using GNU Make 4.3 for quite some time.

I don't know what's going on yet and I'll continue to investigate.

**Comment by dumbbell** [comment]
It looks like the `--no-print-directory` flag is ignored/overridden on the following line:
https://github.com/rabbitmq/rabbitmq-common/blob/bdf29ca83e4a33fd3b2fc1c49f9c17e4b3930167/mk/rabbitmq-dist.mk#L81-L82

Here is the output diff between the run of `make dist` when RabbitMQ is built and the same run inside `make install` called by dh_auto_install(1):
```diff
+make[3]: Entering directory '/home/admin/rabbitmq/rabbitmq-server-3.8.3'
+make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
 bin/rabbitmqadmin
+make[3]: Leaving directory '/home/admin/rabbitmq/rabbitmq-server-3.8.3/deps/rabbitmq_management'
```

The output of that make(1) recipe is eval'd by the calling make(1) and the extra lines cause that eval to fail.

I'm now looking for the reason why the flag is being ignored/overridden.

**Comment by dumbbell** [comment]
@adeptg: Here is a patch to `rabbitmq-dist.mk` which works around the problem:

```diff
diff --git a/mk/rabbitmq-dist.mk b/mk/rabbitmq-dist.mk
index af1e05a..e5e0706 100644
--- a/mk/rabbitmq-dist.mk
+++ b/mk/rabbitmq-dist.mk
@@ -66,8 +66,8 @@ $$(dist_$(1)_ez): $$(if $$(wildcard $(3)/ebin $(3)/include $(3)/priv),\
 ifeq ($$(shell test -f $(3)/rabbitmq-components.mk \
 	&& grep -q '^list-dist-deps::' $(3)/Makefile && echo yes),yes)
 $$(dist_$(1)_ez): $$(patsubst %,$(3)/%, \
-	$$(shell $(MAKE) --no-print-directory -C $(3) list-dist-deps \
-	APP=$(1) VSN=$(2) EZ_DIR=$$(abspath $$(dist_$(1)_ez_dir))))
+	$$(shell env MAKEFLAGS=--no-print-directory $$(MAKE) -C $(3) list-dist-deps \
+	APP=$(1) VSN=$(2) EZ_DIR=$$(abspath $$(dist_$(1)_ez_dir)) 2>/dev/null))
 endif
 
 ERLANGMK_DIST_APPS += $(1)
```

Basically, I pass `--no-print-directory` in a different way to the sub-make. I also drop the sub-make's stderr to ignore the jobserver warning.

It looks like there is an issue with GNU Make 4.3 in the way it passes flags to a sub-make inside `$(shell)` or in the way that sub-make uses `$(MAKEFLAGS)`. Because our `--no-print-directory` is ignored and `--jobserver` doesn't make it either (my guess after seeing the "jobserver unavailable" warning).

What do you think?

**Comment by adeptg** [comment]
Thanks a lot, @dumbbell 
I'm not so good with make, unfortunately, but your patch works for me.
I've created a merge request for the debian team with it https://salsa.debian.org/openstack-team/third-party/rabbitmq-server/-/merge_requests/6/diffs
I hope you don't mind :) Please let me know if I'm wrong. Thanks again!

**Comment by dumbbell** [comment]
That's perfect, thank you!

I didn't report anything to the GNU Make team. It is still unclear to me what's going on. I'm using version 4.3 (on FreeBSD) but didn't see anything wrong with it. On the other hand, debhelper didn't change much w.r.t. make(1)-based builds, so I doubt it is the culprit. If the problem resurfaces at some point, I will dig further.
