### ISSUE TITLE
Switch to a common JSON library that uses maps

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-common#46]
Filing here because there is no better place than a shared internal library.

We've seen a number of cases where proplist really hurt correctness because we cannot tell the difference between an empty JSON object/proplist and an empty list (JSON array), e.g. https://github.com/rabbitmq/rabbitmq-management/issues/75.

We therefore should switch to a JSON library that uses maps. Granted, this means requiring Erlang 17.5 or later, which we were planning on doing for `3.7.0` anyway. We should use the same library
across the board if we can.

Related: https://github.com/rabbitmq/rabbitmq-server/issues/546.

**Comment by hairyhum** [comment]
[Jiffy](https://github.com/davisp/jiffy) and [jsx](https://github.com/talentdeficit/jsx) have maps support. 
Jiffy is using NIF, jsx is native.

**Comment by michaelklishin** [comment]
It would be interesting to investigate two things about Jiffy:

 * Windows support (if it doesn't support Windows, it is a no-go for us)
 * Throughput difference between the two and our current implementation

**Comment by hairyhum** [comment]
@michaelklishin do you mean throughput difference between proplist implementation with mochijson and maps implementations in this libs?

**Comment by michaelklishin** [comment]
Yes, as well as between the two candidate libraries.

**Comment by hairyhum** [comment]
To do so we need example data set representing typical rabbitmq encoded and decoded data (at least with similar depth and size)

**Comment by michaelklishin** [comment]
We need more than one data set, in fact. Some good candidates:

 * List of 100 connections (as of 3.6.0, HTTP API returns up to 100 objects max)
 * List of 100 channels
 * List of 100 queues
 * `GET /api/overview` body with 100 connections, 3000 channels, 3000 queues

Now, these are random but will cover several very commonly used response types with realistic object counts, plus should offer enough variance.

**Comment by michaelklishin** [comment]
As for runtime parameters, there rarely are many of those, and there's less data than e.g. queue objects, plus runtime parameters are never on the hot path. So we can ignore them: any library will be efficient enough for them.

**Comment by essen** [comment]
Erlang.mk currently has an issue compiling jiffy on Windows, but it should be simple enough to fix (it just uses the wrong compiler, it's a 2 hours-ish work, mostly the time it takes to test the change properly). Jiffy is indeed faster but as it's a NIF you can't just compare them on small benchmarks, you have to try them on the running system. The good thing is the APIs are pretty much equivalent (when using maps there should be no difference in the parsed JSON output AFAIK; when not using maps there's only a tiny difference easily handled).

I'm in love with neither. Jiffy is a NIF so there's warnings associated with that, but it handles slices of JSON and cooperates with the scheduler so it should be fine (though I wouldn't bet my life on it). It's well tested so I doubt we will see crashes. Jsx is Erlang so it's slower but on the other hand benefits from compiling it with hipe which reduces the difference between the two and possibly being safer.

For the kind of data I've seen in the HTTP API so far, jsx would perform very well. It would already be faster than mochijson2 anyway.

**Comment by hairyhum** [comment]
Then we can use something like this https://gist.github.com/hairyhum/2fd3e3213867fc51497b to be able to switch between them during testing.

**Comment by michaelklishin** [comment]
To start the evaluation we should simply dump some JSON with `curl` (see above) and run 100K rounds of decoding (parsing) of the 4 payloads, and get median/95% percentile. Encoding is equally important but collecting realistic input data is not as trivial.

**Comment by essen** [comment]
If you're going to measure performance you might want to look at more than these two. For example there's also https://github.com/sile/jsone and at the bottom of the readme the benchmark lists more libraries.

Also we need numbers with/without hipe as the behaviors with hipe may change.

The basho_bench project can run the benchmark and produce useful graphs automatically.

**Comment by hairyhum** [comment]
We can also check jsone.
mochijson2, yawsjson2, and jsonerl looks like have no maps support. 
jsonx is also NIF (and poorly written) so requires lot of testing and fork digging.

**Comment by hairyhum** [comment]
Naive benchmark. 
Data:

"queues"      : 100 queues
"channels"    : 100 channels
"connections" : 100 connections

Randomized values for each key.

https://gist.github.com/hairyhum/142f14584feec50ada50

Tested with https://github.com/si14/erl_json_test

Result data:

Hipe enabled:

```csv
"Parser",     "Test"                      ,"ResultEnc"        ,"ResultDec"
"jiffy",      "queues (121133b)"          ,1947               ,2833
"jiffy",      "channels (64187b)"         ,856                ,832
"jiffy",      "connections (118898b)"     ,1446               ,2714

"mochijson2", "queues (121133b)"          ,1989               ,3820
"mochijson2", "channels (64187b)"         ,912                ,1938
"mochijson2", "connections (118898b)"     ,1649               ,3186

"jsx",        "queues (121133b)"          ,9087               ,5728
"jsx",        "channels (64187b)"         ,3772               ,2191
"jsx",        "connections (118898b)"     ,7489               ,4982

"jsone",      "queues (121133b)"          ,2940               ,3213
"jsone",      "channels (64187b)"         ,1238               ,1670
"jsone",      "connections (118898b)"     ,2682               ,2996
```
Hipe disabled:

```csv
"Parser",           "Test","ResultEnc","ResultDec"
"jiffy",      "queues (121133b)"                  ,2020           ,3037
"jiffy",      "channels (64187b)"                 ,892            ,954
"jiffy",      "connections (118898b)"             ,1595           ,2886

"mochijson2", "queues (121133b)"                  ,4200           ,10628
"mochijson2", "channels (64187b)"                 ,1936           ,4919
"mochijson2", "connections (118898b)"             ,3685           ,8998

"jsx",        "queues (121133b)"                  ,9723           ,8434
"jsx",        "channels (64187b)"                 ,4326           ,3537
"jsx",        "connections (118898b)"             ,7728           ,7628

"jsone",      "queues (121133b)"                  ,7227           ,8207
"jsone",      "channels (64187b)"                 ,3290           ,4323
"jsone",      "connections (118898b)"             ,6487           ,7896
```

Looks like `jsx` have some problems working with HIPE, because results are same with or without it. I have checked in shell that modules is compiled like `native`.

**Comment by essen** [comment]
Just to be sure, those numbers are when creating maps on 18+? (Except mochijson2 of course.)

I'm a bit unsure why mochijson2 encoding would be so fast compared to the others. Is there something it doesn't do?

**Comment by hairyhum** [comment]
This is 18+ (erts-7.1), `jsx` and `jiffy` decodes are configured to decode to maps.
`mochijson2` decode to proplist.

**Comment by hairyhum** [comment]
Mochijson is encoding to iolist and then transformaed to binary by `iolist_to_binary`. Maybe it is the reason of fast encode.

**Comment by essen** [comment]
Encoding to iolist makes perfect sense but `iolist_to_binary` shouldn't be necessary. Something is odd.

Could it be GC? I notice the library you use for testing doesn't do any GC configuration or trigger. It should at least do a full garbage collect before starting a library's benchmark.

**Comment by hairyhum** [comment]
I run `iolist_to_binary` in benchmark to get same result https://github.com/hairyhum/erl_json_test/blob/master/src/erl_json_test.erl#L11

**Comment by hairyhum** [comment]
Using `fullsweep_after=0` and `erlang:garbage_collect` after each batch (batch size = 100)
```
"Parser",     "Test"                        ,"ResultEnc"    ,"ResultDec"
"jiffy",      "queues (121133b)"            ,2102           ,3429
"jiffy",      "channels (64187b)"           ,952            ,1045
"jiffy",      "connections (118898b)"       ,1651           ,3208

"jsx",        "queues (121133b)"            ,10629          ,9748
"jsx",        "channels (64187b)"           ,4916           ,4513
"jsx",        "connections (118898b)"       ,8914           ,7929

"mochijson2", "queues (121133b)"            ,3765           ,12120
"mochijson2", "channels (64187b)"           ,2087           ,6012
"mochijson2", "connections (118898b)"       ,3478           ,11104

"jsone",      "queues (121133b)"            ,7437           ,10870
"jsone",      "channels (64187b)"           ,3640           ,5809
"jsone",      "connections (118898b)"       ,6623           ,10660```

**Comment by essen** [comment]
Oh, I'm silly. I guess the reason why mochijson2 is this fast is because maps currently do not have iterators, so you either needs to maps:to_list or get a list of keys to encode, which is pretty expensive. So the encoding comparison with jsx or jsone is currently not really "fair".

So jiffy is the fastest at everything as expected but is in C, jsone would win at encoding and jsx at decoding otherwise. A bit surprised at the jsx encoding numbers, I would expect encoding to be faster than decoding, not sure what it's doing.

Also despite jiffy seeming to be the clear winner here, I am recommending that if this is what we pick we do benchmarks before/after switching to it on RabbitMQ itself, as bad C code can kill performance. Not saying jiffy is bad though, but bugs happen so you never know.

**Comment by michaelklishin** [comment]
Please specify what unit the results are in.

**Comment by hairyhum** [comment]
Results are taken from `timer:tc`, so it's microseconds

**Comment by essen** [comment]
I observe similar results.

Yesterday I contacted @talentdeficit about the weird behavior with encoding being slower than decoding. He told me he was going to see if he can improve it (jsx isn't doing maps:to_list so perhaps that's why). If this gets fixed it will probably be a fight between jsx and jiffy.

**Comment by talentdeficit** [comment]
does rabbitmq need a general purpose json encoder, or does it mostly encode the same structures over and over? most of the jsx encoding time it taken up by generating an ast from erlang terms but if you know the structure of the term ahead of time there's some relatively easy performance wins you can get by generating the ast directly

**Comment by michaelklishin** [comment]
@talentdeficit a general purpose one.

**Comment by essen** [comment]
Starting work on this. I am planning to have a wrapper module around jsx, jiffy and jsone and remove mochijson2. The wrapper module will use maps for objects.

A compile-time option will allow switching between JSON implementations. I will make the default jsx, arbitrarily, and make sure we can change the default easily.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/issues/546 is in. We now can use/rely on maps and other 18.3+ features.

**Comment by kjnilsson** [comment]
I suspect we do a whole lot more encoding than decoding, at least in terms of the size of the structures involved so an asymmetry between encoding and decoding speeds may not be an issue as long as encoding is the fast one.
