### ISSUE TITLE
Segfault while printing errors to stderr with erlang 18.X

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-common#53]
Looks like code at https://github.com/rabbitmq/rabbitmq-common/blob/b6c0fa46446181ce84b8856f12e50f33481065ff/src/rabbit_misc.erl#L657
is incomptabile with erlang 18.X and its bugs. It causes every other unsuccessful `rabbitmqctl` run to segfault and dump core.

Erlang 18.X VM is really unhappy with things like:
```
./bin/erl -noshell -eval 'Port = open_port({fd, 0, 2}, [out]), port_command(Port, "a"), port_close(Port), erlang:halt(10)'
```

And I think OTP team don't currentl have solution themselves, because they use workarounds like https://github.com/erlang/otp/commit/ba531a173d0dc6906f8492f3bfa0b2cd40e2951a :smile: 

So I think it's better to remove this troublesome piece of code from rabbitmq, because nobody knows then the erlang 18.X itself will be fixed. And because ops use this segfault as an excuse to stop digging into some other problems further :smile:

**Comment by michaelklishin** [comment]
@binarin sounds good. Would you be interested in submitting a PR?

**Comment by binarin** [comment]
Yes, I'll do it.

**Comment by binarin** [comment]
Here is the bug-report for erlang - http://bugs.erlang.org/browse/ERL-91.
According to it  this piece of code in rabbitmq shouldn't cause segfault, but it's still undefined behaviour.
And to be sure that output of `rabbit_misc:format_stderr/2` is flushed after  `erlang:halt/1` is called there are some options:
- Use stdout, flushing guarantee is provided by erlang since 17.0
- Use standard_error with small sleep before calling `erlang:halt/1` - and hope for the better
- Duplicate stderr to some other fd using shell redirection; open port for this fd once and store it to some ETS table; lookup this port in `format_stderr` and send data there.

Last option is bullet-proof (with guarantees from erlang VM), but isn't it too complicated?

**Comment by michaelklishin** [comment]
Yeah, I think option 3 is overkill. I see that the function is only used by `rabbit_cli`, so option 2 may be sufficient.
