### ISSUE TITLE
Feature: Allow using naming patterns when creating a dynamic queue

### ISSUE THREAD

**Issue by vStone** [rabbitmq/rabbitmq-common#95]
Right now, when declaring queues without name, a name is generated using rabbit_guid:gen_secure(). For the sake of identifying these generated queues, it could be useful to use a naming pattern (much like mktemp does) that allows for easy identifying it and still keeping it 'random'.

The main use case would be to identify queues set up by the shovel plugin with more ease.

**Comment by michaelklishin** [comment]
I'm not sure why this is filed for `rabbitmq-common` but you already can attach optional attributes to queues. There are no alternatives as `queue.declare` has a fixed set of fields in the protocol. This sounds like a Shovel/Federation-specific issue, please start a rabbitmq-users thread where other community members can chime in.
